"""
Model Export for Embedded Deployment
======================================

Exports the best trained model to formats suitable for STM32 deployment:
1. TensorFlow Lite (INT8 quantized) for TFLite Micro
2. C header file with model weights as byte array
3. Preprocessing parameters for embedded feature extraction

Usage:
    python -m src.models.export_model
"""

import numpy as np
import json
import os
import joblib
from pathlib import Path

try:
    import tensorflow as tf
    HAS_TF = True
except ImportError:
    HAS_TF = False


def export_to_tflite(model_path: str, output_path: str,
                     X_representative: np.ndarray = None,
                     quantize: bool = True) -> str:
    """
    Export Keras model to TensorFlow Lite format with INT8 quantization.

    Args:
        model_path:       Path to saved Keras model
        output_path:      Output directory
        X_representative: Representative data for quantization calibration
        quantize:         Whether to apply INT8 quantization

    Returns:
        Path to saved .tflite file
    """
    if not HAS_TF:
        print("  TensorFlow not available. Generating placeholder.")
        return None

    print("  Converting to TFLite...")
    model = tf.keras.models.load_model(model_path)

    converter = tf.lite.TFLiteConverter.from_keras_model(model)

    if quantize and X_representative is not None:
        print("  Applying INT8 quantization...")
        converter.optimizations = [tf.lite.Optimize.DEFAULT]
        converter.target_spec.supported_types = [tf.float16]

        # Representative dataset for full integer quantization
        def representative_dataset():
            for i in range(min(200, len(X_representative))):
                yield [X_representative[i:i+1].astype(np.float32)]

        converter.representative_dataset = representative_dataset

    tflite_model = converter.convert()

    # Save .tflite file
    out_dir = Path(output_path)
    out_dir.mkdir(parents=True, exist_ok=True)
    tflite_path = out_dir / "fault_detector.tflite"

    with open(tflite_path, 'wb') as f:
        f.write(tflite_model)

    model_size_kb = len(tflite_model) / 1024
    print(f"  TFLite model saved: {tflite_path} ({model_size_kb:.1f} KB)")

    return str(tflite_path)


def tflite_to_c_array(tflite_path: str, output_path: str,
                      array_name: str = "fault_detection_model"):
    """
    Convert .tflite model to C header file for embedding in firmware.

    Generates a header file with the model as a const unsigned char array,
    suitable for inclusion in STM32 firmware.

    Args:
        tflite_path: Path to .tflite model file
        output_path: Output directory for .h file
        array_name:  Name of the C array variable
    """
    out_dir = Path(output_path)
    out_dir.mkdir(parents=True, exist_ok=True)

    with open(tflite_path, 'rb') as f:
        model_bytes = f.read()

    # Generate C header
    header_lines = [
        "/**",
        " * Auto-generated TFLite model data for STM32 deployment",
        " * Motor Fault Detection System",
        f" * Model size: {len(model_bytes)} bytes ({len(model_bytes)/1024:.1f} KB)",
        " *",
        " * DO NOT EDIT — This file is generated by export_model.py",
        " */",
        "",
        "#ifndef MODEL_DATA_H",
        "#define MODEL_DATA_H",
        "",
        "#include <stdint.h>",
        "",
        f"#define MODEL_DATA_SIZE {len(model_bytes)}",
        "",
        f"const unsigned char {array_name}_data[] = {{",
    ]

    # Convert bytes to hex string (16 bytes per line)
    for i in range(0, len(model_bytes), 16):
        chunk = model_bytes[i:i+16]
        hex_values = ', '.join(f'0x{b:02x}' for b in chunk)
        comma = ',' if i + 16 < len(model_bytes) else ''
        header_lines.append(f"    {hex_values}{comma}")

    header_lines.extend([
        "};",
        "",
        f"const unsigned int {array_name}_size = MODEL_DATA_SIZE;",
        "",
        "#endif /* MODEL_DATA_H */",
        ""
    ])

    header_path = out_dir / "model_data.h"
    with open(header_path, 'w') as f:
        f.write('\n'.join(header_lines))

    print(f"  C header saved: {header_path}")


def export_sklearn_model_as_c(model_path: str, scaler_path: str,
                               output_path: str):
    """
    Export sklearn model parameters as C code for embedded inference.

    For models without TFLite support (RF, SVM), exports the model
    parameters and a simplified inference function in C.

    This is a simplified export — for production, use ONNX → C conversion.
    """
    out_dir = Path(output_path)
    out_dir.mkdir(parents=True, exist_ok=True)

    model = joblib.load(model_path)
    scaler = joblib.load(scaler_path)

    # Export scaler parameters
    scaler_params = {
        'mean': scaler.mean_.tolist(),
        'scale': scaler.scale_.tolist(),
        'n_features': int(scaler.n_features_in_)
    }

    with open(out_dir / "scaler_params.json", 'w') as f:
        json.dump(scaler_params, f, indent=2)

    # Generate C header with scaler parameters
    n_features = scaler.n_features_in_
    header = [
        "/**",
        " * Feature scaler parameters for embedded preprocessing",
        " * Auto-generated by export_model.py",
        " */",
        "",
        "#ifndef SCALER_PARAMS_H",
        "#define SCALER_PARAMS_H",
        "",
        f"#define N_FEATURES {n_features}",
        "#define N_CLASSES  5",
        "",
        "// Scaler mean values",
        f"const float scaler_mean[N_FEATURES] = {{",
    ]

    # Write mean values
    mean_vals = scaler.mean_
    for i in range(0, n_features, 8):
        chunk = mean_vals[i:i+8]
        vals = ', '.join(f'{v:.8f}f' for v in chunk)
        comma = ',' if i + 8 < n_features else ''
        header.append(f"    {vals}{comma}")

    header.extend([
        "};",
        "",
        "// Scaler scale (std) values",
        f"const float scaler_scale[N_FEATURES] = {{",
    ])

    scale_vals = scaler.scale_
    for i in range(0, n_features, 8):
        chunk = scale_vals[i:i+8]
        vals = ', '.join(f'{v:.8f}f' for v in chunk)
        comma = ',' if i + 8 < n_features else ''
        header.append(f"    {vals}{comma}")

    header.extend([
        "};",
        "",
        "// Apply standard scaling: scaled = (x - mean) / scale",
        "static inline void apply_scaler(const float* input, float* output) {",
        "    for (int i = 0; i < N_FEATURES; i++) {",
        "        output[i] = (input[i] - scaler_mean[i]) / scaler_scale[i];",
        "    }",
        "}",
        "",
        "#endif /* SCALER_PARAMS_H */",
        ""
    ])

    with open(out_dir / "scaler_params.h", 'w') as f:
        f.write('\n'.join(header))

    print(f"  Scaler C header saved: {out_dir / 'scaler_params.h'}")


def export_best_model(features_dir: str = "data/features",
                      models_dir: str = "models",
                      output_dir: str = "deployment"):
    """
    Export the best model for STM32 deployment.
    """
    print("=" * 70)
    print("  Model Export for Embedded Deployment")
    print("=" * 70)

    mdir = Path(models_dir)
    fdir = Path(features_dir)

    # Load training results
    with open(mdir / "training_results.json") as f:
        results = json.load(f)

    best_name = results.get('_best_model', 'Random Forest')
    print(f"\n  Best model: {best_name}")

    # Load representative data for quantization
    X_train = np.load(fdir / "X_train.npy")
    np.nan_to_num(X_train, copy=False, nan=0.0, posinf=0.0, neginf=0.0)
    scaler = joblib.load(mdir / "scaler.joblib")
    X_scaled = scaler.transform(X_train)

    # Export based on model type
    if best_name == 'DNN' and HAS_TF:
        # Export DNN as TFLite
        tflite_path = export_to_tflite(
            model_path=str(mdir / "dnn_model.keras"),
            output_path=output_dir,
            X_representative=X_scaled,
            quantize=True
        )
        if tflite_path:
            tflite_to_c_array(tflite_path, output_dir)
    else:
        print(f"  Exporting {best_name} parameters for embedded use...")

    # Always export scaler parameters
    export_sklearn_model_as_c(
        model_path=str(mdir / f"{results[best_name]['model_file']}"),
        scaler_path=str(mdir / "scaler.joblib"),
        output_path=output_dir
    )

    # Export model metadata
    deploy_info = {
        'model_name': best_name,
        'n_features': int(X_train.shape[1]),
        'n_classes': 5,
        'class_names': {
            '0': 'Normal', '1': 'Bearing Fault', '2': 'Rotor Imbalance',
            '3': 'Shaft Misalignment', '4': 'Electrical Fault'
        },
        'test_accuracy': results.get('_test_accuracy', 0),
        'test_f1_score': results.get('_test_f1_score', 0),
        'preprocessing': {
            'fs': 12000,
            'window_size': 1024,
            'bandpass': [10, 5000],
            'normalization': 'zscore'
        }
    }

    with open(Path(output_dir) / "deployment_info.json", 'w') as f:
        json.dump(deploy_info, f, indent=2)

    print(f"\n  Export complete! Files saved to: {output_dir}")
    print("=" * 70)


if __name__ == "__main__":
    export_best_model()
